### PR TITLE
Remove Slack notification from Provision stage

### PR DESCRIPTION
**Pull request by Padgett**
This was creating a lot of unwanted noise

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @Padgett

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by cwebberOps** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: a63dc012-9e45-4f10-9275-be43440aa29f approved by: @cwebberOps

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
