### PR TITLE
I don't think we need this backup folder

### PR DESCRIPTION
**Pull request by jaym**

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
:+1:

**Comment by sersut** [comment]
oh my :+1:

**Comment by schisamo** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: a5620450-4315-46e4-aae9-727d5c27f902 approved by: @schisamo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by oferrigni** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: a5620450-4315-46e4-aae9-727d5c27f902 delivered by: @oferrigni

**Comment by oferrigni** [comment]
All delivered!!

**Pull request merged**
