### PR TITLE
Make /versions endpoint return metadata that has consistent versions.

### PR DESCRIPTION
**Pull request by sersut**
@schisamo @jaym @patrick-wright 

So previously `/versions` endpoint returned you the `latest` for all the existing platforms which was confusing because the versions did not match across the platforms. See the removed json file for an example of what was being returned for chef. 

I have made it so that we return the latest version only for the platforms that are only associated with that version.

I have switched the tests to use chefdk because chef manifest have a version greater than all the other versions (for testing a yolo mode corner case).

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
:+1:

**Comment by sersut** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: d5c75999-e4b1-492f-aba8-de87533f02f8 approved by: @sersut

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by sersut** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: d5c75999-e4b1-492f-aba8-de87533f02f8 delivered by: @sersut

**Pull request merged**
