### PR TITLE
Add basic StatsD metric capturing

### PR DESCRIPTION
**Pull request by schisamo**
/cc @jaym @cwebberOps @sersut

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jaym** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: fe4897ea-0aa3-4aad-a11a-23250eef0522 approved by: @jaym

**Comment by jaym** [comment]
yo

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by jaym** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: fe4897ea-0aa3-4aad-a11a-23250eef0522 delivered by: @jaym

**Pull request merged**
