### PR TITLE
Remove Chef Server from Omnitruck

### PR DESCRIPTION
**Pull request by schisamo**
This just causes confusion as people just pull down an really old out of date CS11. For example:

```
➜  curl "http://www.getchef.com/chef/metadata-server?prerelease=false&nightlies=false&p=ubuntu&pv=12.04&m=x86_64"
url	http://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef-server_11.1.6-1_amd64.deb
md5	d07cf230410b55bd8939ab29d65a3cc5
sha256	b0a27a0b04c30c102d65fa7e2f2f40f64e9cdde7ff07a453a91e1113b52929d8
```

/cc @chef/ociv @chef/client-engineers 

This is for @randomcamel :heart:.

### CODE REVIEW

**Comment by danielsdeleo** [comment]
I haven't checked the code but sounds like the current behavior is really broken, we should ship this. 

Cc: @chef/lob

**Comment by lamont-granquist** [comment]
Could we go the other direction and upload the current Chef12 artifacts to omnitruck buckets?

**Comment by schisamo** [comment]
@lamont-granquist Not sure it's needed as all platforms we support CS12 on support APT/YUM. IMO we should encourage people to use the platform native repositories offered up at:
https://packagecloud.io/chef/current
https://packagecloud.io/chef/stable

Thoughts @chef/lob?

**Comment by stevendanna** [comment]
I can go either way.  In either case (removing the endpoint of having it server chef 12) we need to announce this in advance.

Unlike chef-client, the yum and apt repos cover all of our supported platforms for chef-server, making omnitruck less necessary.

**Comment by schisamo** [comment]
@stevendanna It has never served Chef Server 12 (or EC).

**Comment by tylercloke** [comment]
If it simplifies things and we foresee it staying redundant with distro package managers, then go for it, but do we expect to ever be using a platform where using the native package manager is hard? If not, then go for it imo.

**Comment by lamont-granquist** [comment]
We're already working on an AIX chef server, and there's no apt or yum or anything similar for that platform -- in the useful sense of being able to install over the network and follow a channel and depsolve and everything AIX has no package manager.

**Comment by scotthain** [comment]
@lamont-granquist We are?

**Comment by mattray** [comment]
@lamont-granquist perhaps you're confused about the Linux on POWER port being done? We are porting the server to RHEL 7.1 and Ubuntu 14.04 to Linux on POWER, much simpler than AIX.

**Comment by btm** [comment]
Omnitruck's going to be around for a while. The client's going to end up on more platforms, not less, and packagecloud seems unlikely to be fast on supporting all-the-things. 

I'd check the splunk logs to see if anyone is hitting this endpoint. The big question is, how do you get older versions of Chef Server if you need them if we turn this off? It looks like package cloud only has 11.1.5 and 11.1.6 from 11.x. Are we effectively taking the old versions off the internet if we remove this endpoint?

**Comment by lamont-granquist** [comment]
@mattray ah you're right, i got those confused.

**Comment by schisamo** [comment]
@btm It would probably be best to publish the old versions to PackageCloud (they exist in Artifactory) and update the download page to serve up the PackageCloud URLs. This will make old OSS Chef Server releases consistent with the other server products.

**Comment by stevendanna** [comment]
A simple splunk search:

    index=opscode-platform metadata-server OR full_server_list OR chef_server_platform_names OR download-server

shows that the endpoints removed in this PR have been accessed 4000+ times in the last 24 hours.  So, we should definitely make an announcement regardless of the direction we plan to go.  Many people are making requests with version=latest, so updating omnitruck to serve the 12.0 packages would still likely be an impactful event for some as would removing these endpoints altogether.

I'm +1 on making it easier to get Chef 12, just putting this here as a reminder for us to announce this change.

**Comment by schisamo** [comment]
Thx @stevendanna. It should also be noted `full_server_list` is fetched every time someone the Open Source Chef Server 11 download page (it's used to populate the various drop downs):
https://www.chef.io/download-open-source-chef-server-11/

If we update this download page to work like the other server products (full static generation with PackageCloud URLs) the Splunk logs might tell a different story.

**Comment by sdelano** [comment]
Has there been any movement on this in the last week?

**Comment by schisamo** [comment]
@sdelano No movement. I am planning on cutting the [Open Source Chef Server 11](https://www.chef.io/download-open-source-chef-server-11/) download page over to using packagecloud links sometime this week. That change/decision should be done regardless of whether we completely remove OLD chef-server from Omnitruck...which I still stand by as the right decision.

**Comment by lamont-granquist** [comment]
We definitely either need to remove the old chef-server from omnitruck, or upload chef-server 12 to omnitruck.  The current state is bad.

**Comment by stevendanna** [comment]
Kinda feel someone should just make an executive decision here...

**Comment by btm** [comment]
@stevendanna I got looking at the chef-web-downloads project yesterday. We're moving the client over to use it because after switching to manhattan for builds we're not getting some of the omnitruck related bits that old-ci used to push that would trigger the API to provide yolo for untested versions. It's not clear how we plan to have all of this work together, so I had 1:1 meetings with a handful of people yesterday to try to determine the state and history of how we got here. There are a bunch of people whose mile-high view of how the release infrastructure looks or is going to look is different, and we might need to pounce on that quickly, because we're looking at problems with parts of that infrastructure differently.

**Comment by schisamo** [comment]
@btm @stevendanna Well the Chef Server download page now contains ALL Chef Server releases including older OSC11:
http://downloads.chef.io/chef-server/

This was done almost a month ago in:
https://github.com/chef/chef-web-downloads/pull/185
https://github.com/chef/chef-web-www/commit/6f91cb89de900a392880e19df855aff399205780

I honestly think we should just rebase this onto master and get it deployed.

**Comment by danielsdeleo** [comment]
> It should also be noted full_server_list is fetched every time someone access the Open Source Chef Server 11 download page (it's used to populate the various drop downs):
https://www.chef.io/download-open-source-chef-server-11/
> If we update this download page to work like the other server products (full static generation with PackageCloud URLs) the Splunk logs might tell a different story.

Okay, we did that, so did we get the results we expected?

Also, is it possible to return a `410 Gone` or better yet `301 Moved Permanently` here and have the messaging reach the end user?

I'm in favor of the general idea, we just need to be sure that we make the end-user experience as nice as possible.

**Comment by stevendanna** [comment]
> Okay, we did that, so did we get the results we expected?

Over 5/26/15 8:00:00.000 AM to 5/27/15 8:22:00.000 AM we see 4533 hits on the following query:

    index=opscode-platform sourcetype="nginx-access" metadata-server OR full_server_list OR chef_server_platform_names OR download-server

Some facts about those requests. 

## Request Breakdown
### User-agents

Agent | Count | Percentage
--------|-----------|-----------------
Ruby	|4,217|	93.029%	
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36	|29	|0.64%	
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36	|20	|0.441%	
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0	|17|	0.375%	

There is a long tail of brower-ish user-agents that all clock in at under 1%.

### By Endpoint

Endpoint | Count | Percentage
------------|-----------|---------------
download-server | 4,122 | 90.93%
full_server_list | 307 | 6.7%
metadata-server | 104| 2.29%
chef_server_platform_names | 0 | 0.0%

Looking at just the download-server requests

http_path | count | percentage
-------------|----------|----------------
/chef/download-server?p=el&pv=6&m=x86_64&v=latest&prerelease=false&nightlies=false | 1,625 | 39.423%	
/chef/download-server?p=ubuntu&pv=12.04&m=x86_64&v=latest&prerelease=false&nightlies=false | 1,410 | 34.207%	
/chef/download-server?p=el&pv=6&m=x86_64&v=11.1.6&prerelease=false&nightlies=false | 496 | 12.033%	
/chef/download-server?p=ubuntu&pv=12.04&m=x86_64&v=11.1.6&prerelease=false&nightlies=false | 190 | 4.609%	
/chef/download-server?p=ubuntu&pv=12.04&m=x86_64&v=11.1.6-1&prerelease=false&nightlies=false | 147 | 3.566%	
/chef/download-server?p=ubuntu&pv=12.04&m=x86_64&v=11.1.1&prerelease=false&nightlies=false | 90 | 2.183%	
/chef/download-server?p=el&pv=6&m=x86_64&v=11.0.11&prerelease=false&nightlies=false | 67 | 1.625%	
/chef/download-server?p=ubuntu&pv=12.04&m=x86_64&v=11.1.3&prerelease=false&nightlies=false | 47	| 1.14%	
/chef/download-server?p=ubuntu&pv=12.10&m=x86_64&v=latest&prerelease=false&nightlies=false | 45	| 1.092%

Over 70% of the requests are pulling latests, so changing what that returned would likely impact most of these users.

From the user-agent, my expectation is that these requests are mostly from chef-client runs of people using some version of the chef-server cookbook.

**Comment by danielsdeleo** [comment]
User agent "ruby" is weird because Chef sets the user agent to "Chef Client $version blah blah". Does the chef-server cookbook just use net/http or rest-client directly?

> Over 70% of the requests are pulling latests, so changing what that returned would likely impact most of these users.

Contrarily, the documented behavior for "latest" is to get the latest. If these folks actually don't want CS 12, they've been lucking out. Though that doe make it seem like a hard break by returning 410 might be better than making their cookbook possibly do the wrong thing. :frowning:

**Comment by stevendanna** [comment]
> Does the chef-server cookbook just use net/http or rest-client directly?

Yes: https://github.com/chef-cookbooks/chef-server/blob/chef11/libraries/omnitruck_client.rb#L56
https://github.com/chef-cookbooks/chef-server/blob/chef11/attributes/default.rb#L19

That leads me to believe that almost all uses of that endpoint come from the chef11 version of the chef-server cookbook.

**Comment by stevendanna** [comment]
The following is a plan proposed during a HipChat conversation.  The goal is to reduce the number of people we break while also reducing the confusion around omnitruck and chef server.

1. Make changes to the relevant version line of the chef-server cookbook to convert it to package cloud.
2. Release the new chef-server cookbook and encourage people to upgrade to it.
3. Announce a deprecation date for the omnitruck chef-server endpoints
4. Remove chef-server endpoints from omnitruck on those dates

This plan assumes the following:

- Chef Server packages canonical release location is package cloud.
- Having the omnitruck endpoints serve Chef 12 would be dangerous as the Chef 11 -> 12 upgrade is non-trivial.
- Our end goal is for all chef-server users to install the chef-server packages from our packagecloud repositories or manually by downloading the package.

**Comment by jtimberman** [comment]
The default recipe of the chef-server cookbook [allows setting the version as an attribute](https://github.com/chef-cookbooks/chef-server/blob/master/recipes/default.rb#L28).

Does this work? If so, users can pin their version with the attribute and I don't think we need to make any changes to the cookbook. Unless it is desired to set a version 11 and switch to `chef_server_ingredient` in the 11-stable branch of that cookbook? I don't think we should make a new release to supermarket - the default (latest) version on the site is 12+.

**Comment by stevendanna** [comment]
@jtimberman The context is that we believe the majority of the users of the chef-server omnibus endpoint are users of the 2.x version of this cookbook which uses omnitruck.  If those users can all safely move to the newest version simply by setting the version string to an 11.x version, then that will work; however, it requires that we actually get users on that version.

**Comment by schisamo** [comment]
@adamedx @jdmundrawala Have we gotten this work scheduled?

**Comment by adamedx** [comment]
@charlesjohnson , @mmzyk, looks like people still hit this problem. @echohack has some examples, and given ongoing omnitruck work, now may be a good time to take this.

**Comment by schisamo** [comment]
You can now install any of Chef Software Inc's products using Omnitruck's install script. Full details can be found at https://docs.chef.io/packages.html#omnitruck-install-scripts.

**Pull request closed without merging**
