### PR TITLE
Modify fastly not to cache /_status endpoint. Fix the possible typo in fastly config.

### PR DESCRIPTION
**Pull request by sersut**
/cc: @cwebberOps

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by sersut** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 7bffb2c9-29c8-428b-98a7-36a8e1b21ea7 approved by: @sersut

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by sersut** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 7bffb2c9-29c8-428b-98a7-36a8e1b21ea7 delivered by: @sersut

**Pull request merged**
