### PR TITLE
/versions endpoint currently fails when search for an integration build which is missing for one platform

### PR DESCRIPTION
**Pull request by sersut**
Currently this url 500s in omnitruck:

https://omnitruck.chef.io/current/chef/versions?v=12.4.3%2B20151006083011

The reason is because that integration version is missing from solaris2 platform and because of https://github.com/chef/omnitruck/blob/master/lib/chef/version.rb#L155-L157 we get a version that does not exist in metadata when we are searching. This protects us against that condition.

@schisamo @jaym

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by jaym** [comment]
:+1:

**Comment by sersut** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: d586558a-8a0e-4bee-93a3-ed6568a811ae approved by: @sersut

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by sersut** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: d586558a-8a0e-4bee-93a3-ed6568a811ae delivered by: @sersut

**Pull request merged**
