### PR TITLE
Add missing comma for hash_keys of fastly.

### PR DESCRIPTION
**Pull request by sersut**
/cc: @schisamo @jaym @cwebberOps

### CODE REVIEW

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by sersut** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: b30f2afc-fa1b-4a5d-acd9-1190c81def7d approved by: @sersut

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by sersut** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: b30f2afc-fa1b-4a5d-acd9-1190c81def7d delivered by: @sersut

**Pull request merged**
