### PR TITLE
Omnitruck spec re-write

### PR DESCRIPTION
**Pull request by sersut**
The aim of this PR is to clean up and simplify the specs in omnitruck so that we can be more confident in our changes. There are many files moving around. Reviewing it commit by commit will be more easier. 

First commit:
* Re-writes the app_spec.rb and separates out the most brittle part of the logic (version resolution).
* Also discovered a bug in the way we are handling windows builds and changed the way we are maintaining the windows build information in the cache slightly with @jaym. 

Second commit moves the code that is not applicable to the omnitruck's new setup into a directory called archive so that we can maybe refer to it or maybe delete it in the future. It also moves the code under to `/opscode` to `/chef`.

There will be 3 spec failures. I have left them in for us to discuss.

/cc: @patrick-wright @schisamo

### CODE REVIEW

**Comment by patrick-wright** [comment]
Changes look good overall.  What are your thoughts on handling the iteration number?

**Comment by schisamo** [comment]
Per some [internal discussion](https://chefio.slack.com/archives/_new_omnitruck/p1443812218000404) between @sersut, @jaym and this PR needs to be updated with the following changes:

* Any files that were slated to be moved into the `archive` directory should just be deleted (the git history is our archive).
* omnitruck-verifier should be removed. It needs some major refactoring (ETag + multipart upload shenanigans). An updated solution is forthcoming.

**Comment by sersut** [comment]
@patrick-wright re: iteration number => That should never come out of omnitruck.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by lamont-granquist** [comment]
You might want to look at if you've caught the edge conditions that are tested in these specs:

https://github.com/chef/omnitruck/pull/71/files
https://github.com/chef/omnitruck/pull/98/files

I think the check in 71 probably got dropped already since I don't see the busted "-" version anywhere in the build list files?  It should probably be added some other more obvious way since its a super-stealth ninja test as it was.  I tried grepping through your tests for 98 and couldn't see it, but you might have coverage there some other way?  That one is more about the case we had where el7 wasn't correctly yolo'ing back to el6 versions which might not be obvious from the test case + description.

**Comment by sersut** [comment]
Thanks for checking out @lamont-granquist. I have restored the entry in the build list. I didn't even realize :smile: Also I think I have the yolo mode covered in https://github.com/chef/omnitruck/blob/sersut/spec-rehaul/spec/app_spec.rb#L123

LMK how it looks.

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by schisamo** [comment]
:+1:

**Comment by sersut** [comment]
So what is our general delivery workflow now? Does the creator of the PR makes the delivery magic once it has the necessary number of thumbsups?

**Comment by lamont-granquist** [comment]
I don't think that case captures what #98 was about.  Its making certain that el7 will pick up el6 artifacts (which is even more important now that we're only pushing el5 to el6 and el7)

Although I might be missing something in my reading of your tests...

**Comment by chef-delivery** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by lamont-granquist** [comment]
:+1: 

i think that's good enough on the edge cases i can recall.  if there's any others that got missed, we probably just need to re-discover them again because the old tests were so bad...

**Comment by sersut** [comment]
@delivery approve.

**Comment by chef-delivery** [comment]
Failed to unknown change: 90bf1c30-bb1e-42e7-8bae-294aba636a28
  Delivery does not understand this command. @sersut

**Comment by sersut** [comment]
@delivery approve

**Comment by chef-delivery** [comment]
Change: 90bf1c30-bb1e-42e7-8bae-294aba636a28 approved by: @sersut

**Comment by lamont-granquist** [comment]
lol punctuation =)

**Comment by sersut** [comment]
or a test :)

**Comment by chef-delivery** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by sersut** [comment]
@delivery deliver

**Comment by chef-delivery** [comment]
Change: 90bf1c30-bb1e-42e7-8bae-294aba636a28 delivered by: @sersut

**Pull request merged**
